### ISSUE TITLE
Make your website live.

### ISSUE THREAD

**Issue by DanCQ** [AdityaChaudhary3/Lost-Treasure#1]
I'm not sure if you know how to make your website live free here on GitHub. <br>
I tried to see your Lost Treasure site, but to do so I have to download all your code to my computer. <br>
Anyway, I forked the project and made the site live on my end. I'll try to contribute. <br>

Here's a YouTube tutorial I used:

<a href="https://youtu.be/MTc2CTYoszY">Deploy your website for free with Cloudflare Pages and GitHub!</a>

**Comment by AdityaChaudhary3** [comment]
Thanks for the suggestion.
I make the website live.

**Comment by AdityaChaudhary3** [comment]
Assign to my self.

**Comment by AdityaChaudhary3** [comment]
This issue is actually resolved.
